#
# Copyright 2013-2019 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

jobs:
    - job: Test
      pool:
          vmImage: 'Ubuntu 16.04'
      variables:
          JHI_PROFILE: dev
          JHI_RUN_APP: 1
          JHI_PROTRACTOR: 1
          JHI_ENTITY: sql
          JHI_JDK: 8
          # if JHI_LIB_BRANCH value is release, use the release from Maven
          JHI_LIB_REPO: https://github.com/jhipster/jhipster.git
          JHI_LIB_BRANCH: master
          # if JHI_GEN_BRANCH value is release, use the release from NPM
          JHI_GEN_REPO: https://github.com/jhipster/generator-jhipster.git
          JHI_GEN_BRANCH: master
          # specific config
          SPRING_OUTPUT_ANSI_ENABLED: NEVER
          SPRING_JPA_SHOW_SQL: false
          JHI_DISABLE_WEBPACK_LOGS: true
          JHI_E2E_HEADLESS: true
          JHI_SCRIPTS: $HOME/generator-jhipster/test-integration/scripts

      strategy:
          matrix:
              vuejs-default:
                  JHI_APP: vuejs-default
                  JHI_PROFILE: prod
              vuejs-noi18n:
                  JHI_APP: vuejs-noi18n
                  JHI_PROFILE: prod
              vuejs-fulli18n-es:
                  JHI_APP: vuejs-fulli18n-es
                  JHI_PROFILE: prod
              vuejs-gateway:
                  JHI_APP: vuejs-gateway
              vuejs-gradle-session:
                  JHI_APP: vuejs-gradle-session
              vuejs-ws-theme:
                  JHI_APP: vuejs-ws-theme
              vuejs-oauth2:
                  JHI_APP: vuejs-oauth2

      steps:
          #----------------------------------------------------------------------
          # Install all tools and check configuration
          #----------------------------------------------------------------------
          - task: NodeTool@0
            inputs:
                versionSpec: '10.16.0'
            displayName: 'TOOLS: install Node.js'
          - script: |
                if [[ $JHI_JDK = '11' ]]; then
                    echo '*** Using OpenJDK 11'
                    curl -s get.sdkman.io | bash
                    echo sdkman_auto_answer=true > ~/.sdkman/etc/config
                    source "$HOME/.sdkman/bin/sdkman-init.sh"
                    sdk install java 11.0.2-open
                    java --version
                else
                    echo '*** Using OpenJDK 8 by default'
                fi
            displayName: 'TOOLS: configuring OpenJDK'
          - script: |
                wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
                sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
                sudo apt update
                sudo apt install google-chrome-stable
            displayName: 'TOOLS: install google-chrome-stable'
          - script: npm install -g npm
            displayName: 'TOOLS: update NPM'
          - script: npm install -g yarn
            displayName: 'TOOLS: install Yarn'
          - bash: test-integration/scripts/01-display-configuration.sh
            displayName: 'TOOLS: display configuration'
          - bash: test-integration/scripts/03-system.sh
            displayName: 'TOOLS: configure tools installed by the system'
          - bash: test-integration/scripts/04-git-config.sh
            displayName: 'TOOLS: configure git'

          #----------------------------------------------------------------------
          # Install JHipster and generate project+entities
          #----------------------------------------------------------------------
          - bash: test-integration/scripts/10-install-jhipster-vuejs.sh
            displayName: 'GENERATION: install JHipster with Vue.js'
          - bash: $(JHI_SCRIPTS)/11-generate-entities.sh
            displayName: 'GENERATION: entities'
          - bash: test-integration/scripts/12-generate-project-vuejs.sh
            displayName: 'GENERATION: project'
          - bash: $(JHI_SCRIPTS)/13-replace-version-generated-project.sh
            displayName: 'GENERATION: replace version in generated project'
          - bash: $(JHI_SCRIPTS)/14-jhipster-info.sh
            displayName: 'GENERATION: jhipster info'

          #----------------------------------------------------------------------
          # Bugs fix
          #----------------------------------------------------------------------
          - bash: $(JHI_SCRIPTS)/20-no-memory-limit-elasticsearch.sh
            displayName: 'BUGS-FIX: no memory limit for Elasticsearch'

          #----------------------------------------------------------------------
          # Launch tests
          #----------------------------------------------------------------------
          - bash: $(JHI_SCRIPTS)/20-docker-compose.sh
            displayName: 'TESTS: Start docker-compose containers'
          - bash: $(JHI_SCRIPTS)/21-tests-backend.sh
            displayName: 'TESTS: backend'
          - bash: $(JHI_SCRIPTS)/22-tests-frontend.sh
            displayName: 'TESTS: frontend'
          - bash: $(JHI_SCRIPTS)/23-package.sh
            displayName: 'TESTS: packaging'
          - bash: $(JHI_SCRIPTS)/24-tests-e2e.sh
            displayName: 'TESTS: End-to-End'
